### ISSUE TITLE
Question: Will there be support for the MAX32660?

### ISSUE THREAD

**Issue by odo2063** [MaximIntegratedMicros/arduino-max326xx#10]
Will there be support for the MAX32660?

**Comment by khariya** [comment]
Currently, there's no decision made about adding support for MAX32660.

**Comment by SunboX** [comment]
any news?

**Comment by technoblogy** [comment]
I would be very interested in this too, such as on the MAX32660 Evaluation System.

**Comment by khariya** [comment]
We appreciate your interest in the support for MAX32660 but as of now, we don't have a plan to add this to the Arduino platform.

**Comment by technoblogy** [comment]
Thank you for answering anyway!
