### ISSUE TITLE
Low-level pin register query macros issue

### ISSUE THREAD

**Issue by MagSem** [MaximIntegratedMicros/arduino-max326xx#11]
Many libraries (for example, graphics libs UTFT and ucglib ) do not compile due to the lack of a low-level macros block in Maxim Integrateds variant.h.

These macros are missing:
// Low-level pin register query macros
// -----------------------------------
#define digitalPinToPort(P)      (&(PORT->Group[g_APinDescription[P].ulPort]))
#define digitalPinToBitMask(P)   (1 << g_APinDescription[P].ulPin)
//#define analogInPinToBit(P)    ()
#define portOutputRegister(port) (&(port->OUT.reg))
#define portInputRegister(port)  (&(port->IN.reg))
#define portModeRegister(port)   (&(port->DIR.reg))
#define digitalPinHasPWM(P)      (g_APinDescription[P].ulPWMChannel != NOT_ON_PWM || g_APinDescription[P].ulTCChannel != NOT_ON_TIMER)

**Comment by Gerriko** [comment]
Hello is anybody out there... or is this board now "abandonware" considering that this was raised over 1 year ago and no response or fix from Maxim Integrated.

**Comment by MagSem** [comment]
Yes, they thought it was enough to make a good board, and programmers are optional.

**Comment by jessexm** [comment]
arduino-max326xx repo has been archived and is now read only.
