### ISSUE TITLE
Please add support for MAX32660

### ISSUE THREAD

**Issue by SunboX** [MaximIntegratedMicros/arduino-max326xx#14]
I would love to have support for the MAX33660-EVSYS, because it would simplify development a lot.

Using Eclipse and CMSIS API is way more complex and "undocumented" than using Arduino / PlatformIO. There are less Libraries and also less Resources in case of "I have this issue, how can I solve it".

**Comment by khariya** [comment]
I understand your concern but we don't have a plan to support MAX32660 at present.

**Comment by yahaggach** [comment]
I second this support for MAX32660 would be highly appreciated ... Is there a place where we can submit such requests for consideration ?
