### ISSUE TITLE
Please add Support for MAX32625PICO board

### ISSUE THREAD

**Issue by SunboX** [MaximIntegratedMicros/arduino-max326xx#15]
Can you please add support for the MAX32625PICO board. Or is it already supported out of the box, but not mentioned in the readme?

**Comment by khariya** [comment]
MAX32625PICO is not supported as a target on the Arduino platform. It is used as a programmer for the [currently supported boards](https://github.com/MaximIntegratedMicros/arduino-max326xx/wiki#status). We will update the status if add new boards.
