### ISSUE TITLE
How to change pin voltage of MAX32630FTHR?

### ISSUE THREAD

**Issue by idea--list** [MaximIntegratedMicros/arduino-max326xx#16]
Hi there,

I noticed most pins have a voltage of about 0.01V which is simply not enough to drive any wings.
In Mbed OS i start all my programs by `MAX32630FTHR pegasus(MAX32630FTHR::VIO_3V3);` to set all the pins to 3.3V.

What is the equivalent for that line with this Arduino core?

**Comment by khariya** [comment]
`useVDDIOH(pin)` will set pin to 3.3v. Please see [API page](https://github.com/MaximIntegratedMicros/arduino-max326xx/wiki/API) for details.

**Comment by idea--list** [comment]
Thanks!
