### ISSUE TITLE
Missing USB drivers

### ISSUE THREAD

**Issue by Gerriko** [MaximIntegratedMicros/arduino-max326xx#19]
Usually within the core Arduino hardware packages for different boards you will find USBdrivers for HID, keyboard, mouse etc.
This is missing here. As such, none of the default examples found within the "09. USB" folder will compile making these boards non compliant with the Arduino eco system.

I note that there are some old Mbed drivers for USB available for the max326xx boards, but it would require some modification by yourselves.

https://os.mbed.com/teams/MaximIntegrated/code/USBDevice/

Any plans to do so, or what is stopping this from being implemented.

Thanks.

**Comment by jessexm** [comment]
arduino-max326xx repo has been archived and is now read only.
