### ISSUE TITLE
Link showing 404 error

### ISSUE THREAD

**Issue by SoumilPsiBorg** [MaximIntegratedMicros/arduino-max326xx#20]
Provided link for Maxim integrated board is not working now . kindly solve the issue as soon as possible

**Comment by rmarcus1tul** [comment]
The link has still not been updated. Is this repository (along with the other tools associated with the MAX32630FTHR EVK) now deprecated?

**Comment by Jake-Carter** [comment]
Apologies for the delay.  This repo was unmaintained after our migration to the analogdevicesinc org.

I've just updated the repo with a new package manager URL now and the README has been updated.  Please use:

```
https://raw.githubusercontent.com/analogdevicesinc/arduino-max326xx/master/package_maxim_index.json
```
