### ISSUE TITLE
Bootloader file for MAX32630FTHR

### ISSUE THREAD

**Issue by renatosc** [MaximIntegratedMicros/arduino-max326xx#7]
I am trying to Burn Bootloader for MAX32630FTHR but I am getting that following error:

 

> /Users/user/Library/Arduino15/packages/Maxim/tools/daplink/1.0.2/bootloader/max3263x_fthr_bl.bin: No such file or directory
> Error while burning bootloader.

in the Arduino IDE console.

**Comment by khariya** [comment]
@renatosc  The bootloader is only available for MAX32620FTHR board.

**Comment by renatosc** [comment]
I see. Would you perhaps know how do I then do a "factory reset" on MAX32630FTHR?

**Comment by khariya** [comment]
The latest MAX32630FTHR has a Blink program loaded out of the box. It blinks the red LED forever when powered on.
Factory reset is no different than uploading a Blink example from Arduino IDE.
