### ISSUE TITLE
SD issue

### ISSUE THREAD

**Issue by idea--list** [MaximIntegratedMicros/arduino-max326xx#9]
Have a project that would need the SD card functionality of my MAX32630FTHR board.
Using arduino v1.8.9 and maxim's 32-bit microcontroller v1.1.5 the SD functionality does not work, though i have set P0_7 as chipselect pin..
Tried all the SD code examples bundled to arduino but none of them work. The SD card itself has no issues.

**Comment by khariya** [comment]
Are you using [SD Library](https://www.arduino.cc/en/Reference/SD) with one of [these examples](https://www.arduino.cc/en/Tutorial/LibraryExamples#sd)?
The SD Library uses different pin connections than the ones on [MAX32630FTHR board](https://github.com/MaximIntegratedMicros/arduino-max326xx/wiki/MAX32630FTHR#peripheral-interfaces). Please modify the pins accordingly in your existing library.

**Comment by idea--list** [comment]
Yes, i am using those examples.
I modified Sd2Card.h file like that `/**
 * SD Chip Select pin
 *
 * Warning if this pin is redefined the hardware SS will pin will be enabled
 * as an output by init().  An avr processor will not function as an SPI
 * master unless SS is set to output mode.
 */
#ifndef SDCARD_SS_PIN
/** The default chip select pin for the SD card is SS. */
//uint8_t const  SD_CHIP_SELECT_PIN = SS;
uint8_t const  SD_CHIP_SELECT_PIN = 7;
#else
//uint8_t const  SD_CHIP_SELECT_PIN = SDCARD_SS_PIN;
uint8_t const  SD_CHIP_SELECT_PIN = 7;
#endif

// The following three pins must not be redefined for hardware SPI,
// so ensure that they are taken from pins_arduino.h or variant.h, depending on architecture.
#ifndef SDCARD_MOSI_PIN
/** SPI Master Out Slave In pin */
//uint8_t const  SPI_MOSI_PIN = MOSI;
uint8_t const  SPI_MOSI_PIN = 5;
/** SPI Master In Slave Out pin */
//uint8_t const  SPI_MISO_PIN = MISO;
uint8_t const  SPI_MISO_PIN = 6;
/** SPI Clock pin */
//uint8_t const  SPI_SCK_PIN = SCK;
uint8_t const  SPI_SCK_PIN = 4;
#else
//uint8_t const  SPI_MOSI_PIN = SDCARD_MOSI_PIN;
//uint8_t const  SPI_MISO_PIN = SDCARD_MISO_PIN;
//uint8_t const  SPI_SCK_PIN = SDCARD_SCK_PIN;
uint8_t const  SPI_MOSI_PIN = 5;
uint8_t const  SPI_MISO_PIN = 6;
uint8_t const  SPI_SCK_PIN = 4;
#endif`

I took those pinnumbers from `Users/USER/Documents/Arduino/packages/Maxim/hardware/arm/1.1.5/variants/max3263x_fthr/variant.h`. Recompiled and uploaded the sketch on the board, but nothing changes. I can not make SD work.

Do you have any idea what i might be doing wrong?

**Comment by jessexm** [comment]
arduino-max326xx repo has been archived and is now read only.
